<?php

/**
 *  Website that displays live PHP documentation of classes and functions with the help of reflection.
 *  Copyright (C) 2015  Marcel Joachim Kloubert <marcel.kloubert@gmx.net>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *  
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


require PLD_DIR_VIEWS . 'common_view_include.php';

?>
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>phpLiveDoc :: <?php echo htmlentities($this->title); ?></title>
    
    <!--  highlight.js  -->
    <link href="css/highlight/default.css" rel="stylesheet">
    
    <link rel="stylesheet" href="css/foundation.css" />
    
    <link rel="stylesheet" href="css/style.css" />
    
    <script src="js/vendor/modernizr.js"></script>
  </head>
  
  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">phpLiveDoc</a></h1>
        </li> <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        
        <li class="toggle-topbar menu-icon">
          <a href="#"><span>Menu</span></a>
        </li>
      </ul>
      
      <section class="top-bar-section">
        <!-- Left Nav Section -->
        <ul class="left">
          <li class="has-form">
            <div class="row collapse">
              <div class="large-8 small-9 columns">
                <input type="text">
              </div>
              
              <div class="large-4 small-3 columns">
                <a href="#" class="alert button expand">Search</a>
              </div>
            </div>
          </li>
        </ul>
      </section>
    </nav>
  
    <div id="PLDContent">
        <div class="row"><?php echo $this->content; ?></div>
      </div>
    
    <script src="js/vendor/jquery.js"></script>
    <script src="js/vendor/highlight.pack.js"></script>
    <script src="js/foundation.min.js"></script>
    <script src="js/jsToolbox.min.js"></script>
    
    <script>
        $jsTB.page.addOnLoaded(function() {
            hljs.initHighlighting();
        });
    
        $(document).foundation();
    </script>
  </body>
</html>